// <auto-generated />
using ApiOnlineShopWeb.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiOnlineShopWeb.Migrations
{
    [DbContext(typeof(ApiOnlineShopWebContext))]
    [Migration("20240703203245_AddedProduct")]
    partial class AddedProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiOnlineShopWeb.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Name = "Persil",
                            Picture = "persil.jpg",
                            Price = 5.99m,
                            Producer = "Henkel"
                        },
                        new
                        {
                            Id = 2,
                            Category = 4,
                            Name = "Inkpad 4",
                            Picture = "inkpad4.jpg",
                            Price = 239.99m,
                            Producer = "Pocketbook"
                        },
                        new
                        {
                            Id = 3,
                            Category = 2,
                            Name = "Giotto",
                            Picture = "giotto.jpg",
                            Price = 2.99m,
                            Producer = "Ferrero"
                        },
                        new
                        {
                            Id = 4,
                            Category = 3,
                            Name = "Reis",
                            Picture = "reis.jpg",
                            Price = 0.99m,
                            Producer = "Bioland"
                        });
                });

            modelBuilder.Entity("ApiOnlineShopWeb.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EMail = "igor@gmail.com",
                            Name = "Igor Il",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            EMail = "yury@gmail.com",
                            Name = "Yury Spi",
                            Password = "123456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
