// <auto-generated />
using ApiUser.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiUser.Migrations
{
    [DbContext(typeof(ApiUserContext))]
    partial class ApiUserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiUser.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 34,
                            City = "Hamburg",
                            Country = "Germany",
                            EMail = "igor@gmail.com",
                            GivenName = "Igor",
                            HouseNumber = 154,
                            Password = "123456",
                            PostalCode = 22526,
                            Street = "Berner Chaussee",
                            Surname = "Il"
                        },
                        new
                        {
                            Id = 2,
                            Age = 38,
                            City = "Harburg",
                            Country = "Germany",
                            EMail = "yury@gmail.com",
                            GivenName = "Yury",
                            HouseNumber = 22,
                            Password = "123456",
                            PostalCode = 22041,
                            Street = "Harburger Chaussee",
                            Surname = "Spi"
                        },
                        new
                        {
                            Id = 3,
                            Age = 33,
                            City = "Berlin",
                            Country = "Germany",
                            EMail = "dirk@gmail.com",
                            GivenName = "Dirk",
                            HouseNumber = 232,
                            Password = "123456",
                            PostalCode = 25014,
                            Street = "Berliner Straße",
                            Surname = "Es"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
